version: '3.8'
services:
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      # MongoDB errors next start without named volume
      - db-data:/data/db
    environment:
      - 'MONGO=$MONGO'
      - 'MONGO_PORT=$MONGO_PORT'
      - 'MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_USERNAME'
      - 'MONGO_INITDB_ROOT_PASSWORD:$MONGO_INITDB_ROOT_PASSWORD'
      - 'MONGO_INITDB_DATABASE:$MONGO_INITDB_DATABASE'
volumes:
  db-data:
